### ISSUE TITLE
Grundlegende Funktion von einem PHP-Modul nicht umgesetzt

### ISSUE THREAD

**Issue by Nall-chan** [Brovning/solvis#3]
Ein PHP-Modul in Symcon erzeugt niemals fremde Instanzen (hier Modbus) oder konfiguriert Instanzen (Modbus Decive, Gateway, IO).

Ein Modul nutzt vorhandene IOs und Splitter um über den Datenaustausch z.b. ModBus Daten abzufragen und diese dann selbst als Statusvariablen darzustellen.
Es verhält sich dann wie alle anderen Instanzen in Symcon und bildet die Funktion selbstständig ab.

Sehr empfehlenswert ist das Symcon PHP-Modul zum EM24-DIN. Dieses zeigt wie man mit dem Modbus-Gateway innerhalb von Symcon Daten abfragt und diese als Statusvariablen darstellt.

https://github.com/symcon/SymconBC/tree/master/EM24-DIN

**Comment by Brovning** [comment]
Hallo,

Das wurde mir vor ca. 1,5 Jahren bereits zu meinem Fronius und E3DC Modul mitgeteilt. 
Von niemandem, der die Module wirklich nutz, kam ein ähnliches Feedback.
--> won't fix

**Comment by Nall-chan** [comment]
Vielleicht weil User keine Modul Entwickler sind?
Sehr empfehlenswert, sonst wird das Modul nicht durch den Review vom Store kommen:
https://gist.github.com/paresy/236bfbfcb26e6936eaae919b3cfdfc4f
Thema dazu:
https://community.symcon.de/t/draft-best-practice-zur-php-modul-erstellung/44274

**Comment by Brovning** [comment]
Ja, ich weis. Spielt für mich und meine User aber keine Rolle, ob es als Beta im Store ist oder per Modul Control installiert wird.
Ich persönlich finde die Installation per Modul Control ohnehin wesentlich besser/praktischer für alle Seiten.

Wenn ich im Winter ganz viel Zeit habe und mir extrem langweilig ist, gehe ich das Thema vielleicht an...
Ansonsten funktioniert weiterhin auch so alles.
